---
title: "27_09_2019_Notes"
author: "John D."
date: "September 24, 2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rethinking)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```

# 9 Markov Chain Monte Carlo
## 9.1. Good King Markov and His island kingdom

```{r}
num_weeks <- 100
positions <- rep(0,num_weeks)
current <- 10
for ( i in 1:num_weeks ) {
  # record current position
  positions[i] <- current
  # flip coin to generate proposal
  proposal <- current + sample( c(-1,1) , size=1 )
  # now make sure he loops around the archipelago
  if ( proposal < 1 ) proposal <- 10
  if ( proposal > 10 ) proposal <- 1
  # move?
  prob_move <- proposal/current
  current <- ifelse( runif(1) < prob_move , proposal , current )
}
df <- cbind.data.frame(island = positions, week = seq(1,100))
ggplot(df, aes(x=week, y=island)) +
  geom_line()
num_weeks <- 1e5
positions <- rep(0,num_weeks)
current <- 10
for ( i in 1:num_weeks ) {
  # record current position
  positions[i] <- current
  # flip coin to generate proposal
  proposal <- current + sample( c(-1,1) , size=1 )
  # now make sure he loops around the archipelago
  if ( proposal < 1 ) proposal <- 10
  if ( proposal > 10 ) proposal <- 1
  # move?
  prob_move <- proposal/current
  current <- ifelse( runif(1) < prob_move , proposal , current )
}
df <- cbind.data.frame(island = positions, week = seq(1,1e5))
ggplot(df, aes(x=island)) +
  geom_histogram()
```

```{r}
## Any island
num_weeks <- 100
positions <- rep(0,num_weeks)
current <- 10
islands <- 1:10
for ( i in 1:num_weeks ) {
  # record current position
  positions[i] <- current
  # flip coin to generate proposal
  proposal <- sample(islands[-current], size=1 )
  # move?
  prob_move <- proposal/current
  current <- ifelse( runif(1) < prob_move , proposal , current )
}
df <- cbind.data.frame(island = positions, week = seq(1,100))
ggplot(df, aes(x=week, y=island)) +
  geom_point()

num_weeks <- 1e5
positions <- rep(0,num_weeks)
current <- 10
islands <- 1:10
for ( i in 1:num_weeks ) {
  # record current position
  positions[i] <- current
  # flip coin to generate proposal
  proposal <- sample(islands[-current], size=1 )
  # move?
  prob_move <- proposal/current
  current <- ifelse( runif(1) < prob_move , proposal , current )
}
df <- cbind.data.frame(island = positions, week = seq(1,1e5))
ggplot(df, aes(x=island)) +
  geom_histogram(bins=10)
```

## 9.2. Metropolis, Gibbs, and Sadness
### 9.2.1. Gibbs sampling
### 9.2.2. High-dimensional sadness

```{r}
D <- 10
T <- 1e3
Y <- rmvnorm(T,rep(0,D),diag(D))
rad_dist <- function( Y ) sqrt( sum(Y^2) )
Rd <- sapply( 1:T , function(i) rad_dist( Y[i,] ) )
dens( Rd )
```