---
title: "08_10_2020_Notes"
author: "John D."
date: "8/10/2020"
output:
  github_document:
    pandoc_args: --webtex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rethinking)
library(tidyverse)
```

# 16. Generalized Linear Madness
## 16.1. Geometric people
### 16.1.1. The scientific model
### 16.1.2. The statistical model

```{r Rcode 16.1}
data(Howell1)
d <- Howell1
# scale observed variables
d$w <- d$weight / mean(d$weight)
d$h <- d$height / mean(d$height)
```

```{r R code 16.2}
m16.1 <- ulam(
  alist(
    w ~ dlnorm(mu , sigma),
    exp(mu) <- 3.141593 * k * p ^ 2 * h ^ 3,
    p ~ beta(2 , 18),
    k ~ exponential(0.5),
    sigma ~ exponential(1)
  ),
  data = d ,
  chains = 4 ,
  cores = 4
)

precis(m16.1)
pairs(m16.1)
```

```{r R code 16.3}
h_seq <- seq(from = 0 ,
             to = max(d$h) ,
             length.out = 30)
w_sim <- sim(m16.1 , data = list(h = h_seq))
mu_mean <- apply(w_sim , 2 , mean)
w_CI <- apply(w_sim , 2 , PI)
plot(
  d$h ,
  d$w ,
  xlim = c(0, max(d$h)) ,
  ylim = c(0, max(d$w)) ,
  col = rangi2 ,
  lwd = 2 ,
  xlab = "height (scaled)" ,
  ylab = "weight (scaled)"
)
lines(h_seq , mu_mean)
shade(w_CI , h_seq)
```

### 16.1.3. GLM in disguise
## 16.2. Hidden minds and observed behavior

```{r R code 16.4}
data(Boxes)
precis(Boxes)
```

```{r R code 16.5}
table( Boxes$y ) / length( Boxes$y )
```

### 16.2.1. The scientific model

```{r R code 16.6}
set.seed(7)
N <- 30 # number of children

# half are random
# sample from 1,2,3 at random for each
y1 <- sample(1:3 , size = N / 2 , replace = TRUE)

# half follow majority
y2 <- rep(2 , N / 2)

# combine and shuffle y1 and y2
y <- sample(c(y1, y2))

# count the 2s
sum(y == 2) / N
```

### 16.2.2. The statistical model
### 16.2.3. Coding the statistical model

```{r R code 16.7}
data(Boxes_model)
cat(Boxes_model)
```

```{r R code 16.8}
# prep data
dat_list <- list(
  N = nrow(Boxes),
  y = Boxes$y,
  majority_first = Boxes$majority_first
)

# run the sampler
m16.2 <-
  stan(
    model_code = Boxes_model ,
    data = dat_list ,
    chains = 3 ,
    cores = 3
  )

# show marginal posterior for p
p_labels <-
  c("1 Majority",
    "2 Minority",
    "3 Maverick",
    "4 Random",
    "5 Follow First")
plot(precis(m16.2, 2) , labels = p_labels)
```

### 16.2.4. State space models