---
title: "12_6_2019_Notes"
author: "John D."
date: "December 6, 2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rethinking)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```

## 12.3. Ordered categorical outcomes
### 12.3.1. Example: Moral intuition

```{r}
library(rethinking)
data(Trolley)
d <- Trolley
```

### 12.3.2. Describing an ordered distribution with intercepts
```{r}
simplehist( d$response , xlim=c(1,7) , xlab="response" )
```

```{r}
# discrete proportion of each response value
pr_k <- table( d$response ) / nrow(d)
# cumsum converts to cumulative proportions
cum_pr_k <- cumsum( pr_k )
# plot
plot( 1:7 , cum_pr_k , type="b" , xlab="response" ,
ylab="cumulative proportion" , ylim=c(0,1) )
```

```{r}
round( lco <- logit( cum_pr_k ) , 2 )
```

```{r}
m12.4 <- ulam(
  alist(R ~ dordlogit(0 , cutpoints),
        cutpoints ~ dnorm(0 , 1.5)) ,
  data = list(R = d$response),
  chains = 4 ,
  cores = 4
)
```

```{r}
m12.4q <- quap(
  alist(response ~ dordlogit(0 , c(a1, a2, a3, a4, a5, a6)),
        c(a1, a2, a3, a4, a5, a6) ~ dnorm(0 , 1.5)) ,
  data = d ,
  start = list(
    a1 = -2,
    a2 = -1,
    a3 = 0,
    a4 = 1,
    a5 = 2,
    a6 = 2.5
  )
)
```

```{r}
precis( m12.4 , depth=2 )
```

```{r}
round( inv_logit(coef(m12.4)) , 3 )
```

### 12.3.3. Adding predictor variables

```{r}
round( pk <- dordlogit( 1:7 , 0 , coef(m12.4) ) , 2 )
sum( pk*(1:7) )
round( pk <- dordlogit( 1:7 , 0 , coef(m12.4)-0.5 ) , 2 )
sum( pk*(1:7) )
```

```{r}
dat <- list(
  R = d$response,
  A = d$action,
  I = d$intention,
  C = d$contact
)
m12.5 <- ulam(
  alist(
    R ~ dordlogit(phi , cutpoints),
    phi <- bA * A + bC * C + BI * I ,
    BI <- bI + bIA * A + bIC * C ,
    c(bA, bI, bC, bIA, bIC) ~ dnorm(0 , 0.5),
    cutpoints ~ dnorm(0 , 1.5)
  ) ,
  data = dat ,
  chains = 4 ,
  cores = 4
)
precis(m12.5)
```

```{r}
plot( precis(m12.5) , xlim=c(-1.4,0) )
```

```{r}
plot( NULL , type="n" , xlab="intention" , ylab="probability" ,
xlim=c(0,1) , ylim=c(0,1) , xaxp=c(0,1,1) , yaxp=c(0,1,2) )

kA <- 0 # value for action
kC <- 0 # value for contact
kI <- 0:1 # values of intention to calculate over
pdat <- data.frame(A=kA,C=kC,I=kI)
phi <- link( m12.5 , data=pdat )$phi

post <- extract.samples( m12.5 )
for ( s in 1:50 ) {
pk <- pordlogit( 1:6 , phi[s,] , post$cutpoints[s,] )
for ( i in 1:6 ) lines( kI , pk[,i] , col=grau(0.1) )
}
```

```{r}
kA <- 0 # value for action
kC <- 1 # value for contact
kI <- 0:1 # values of intention to calculate over
pdat <- data.frame(A=kA,C=kC,I=kI)
s <- sim( m12.5 , data=pdat )
simplehist( s , xlab="response" )
```

### 12.4. Ordered categorical predictors

```{r}
levels(d$edu)
```

```{r}
edu_levels <- c( 6 , 1 , 8 , 4 , 7 , 2 , 5 , 3 )
d$edu_new <- edu_levels[ d$edu ]
```

```{r}
library(gtools)
set.seed(1805)
delta <- rdirichlet( 10 , alpha=rep(2,7) )
str(delta)
```

```{r}
h <- 3
plot(
  NULL ,
  xlim = c(1, 7) ,
  ylim = c(0, 0.4) ,
  xlab = "index" ,
  ylab = "probability"
)
for (i in 1:nrow(delta))
  lines(
    1:7 ,
    delta[i, ] ,
    type = "b" ,
    pch = ifelse(i == h, 16, 1) ,
    lwd = ifelse(i == h, 4, 1.5) ,
    col = ifelse(i == h, "black", col.alpha("black", 0.7))
  )
```

```{r}
dat <- list(
  R = d$response ,
  action = d$action,
  intention = d$intention,
  contact = d$contact,
  E = as.integer(d$edu_new),
  # edu_new as an index
  alpha = rep(2 , 7)
) # delta prior

m12.6 <- ulam(
  alist(
    R ~ ordered_logistic(phi , kappa),
    phi <-
      bE * sum(delta_j[1:E]) + bA * action + bI * intention + bC * contact,
    kappa ~ normal(0 , 1.5),
    c(bA, bI, bC, bE) ~ normal(0 , 1),
    vector[8]:delta_j <<- append_row(0 , delta),
    simplex[7]:delta ~ dirichlet(alpha)
  ),
  data = dat ,
  chains = 4 ,
  cores = 4 ,
  coerce_int = FALSE
)

precis( m12.6 , depth=2 , omit="kappa" )

delta_labels <- c("Elem","MidSch","SHS","HSG","SCol","Bach","Mast","Grad")
pairs( m12.6 , pars="delta" , labels=delta_labels )

```

```{r}
dat$edu_norm <- normalize(d$edu_new)
m12.7 <- ulam(
  alist(
    R ~ ordered_logistic(mu , cutpoints),
    mu <- bE * edu_norm + bA * action + bI * intention + bC * contact,
    c(bA, bI, bC, bE) ~ normal(0 , 1),
    cutpoints ~ normal(0 , 1.5)
  ),
  data = dat ,
  chains = 4 ,
  cores = 4
)

precis(m12.7)
```

