---
title: "Notes"
author: "John D."
date: "08_31_2020"
output:
  github_document:
    pandoc_args: --webtex
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rethinking)
library(tidyverse)
```

# 11 God Spiked the Integers
## 11.1. Binomial regression
### 11.1.1. Logistic regression: Prosocial chimpanzees
#### R code 11.1
```{r}
library(rethinking)
data(chimpanzees)
d <- chimpanzees
```

#### R code 11.2
```{r}
d$treatment <- 1 + d$prosoc_left + 2*d$condition
```

#### R code 11.3
```{r}
xtabs( ~ treatment + prosoc_left + condition , d )
```

#### R code 11.4
```{r}
m11.1 <- quap(alist(pulled_left ~ dbinom(1 , p) ,
                    logit(p) <- a ,
                    a ~ dnorm(0 , 10)) , data = d)
```

#### R code 11.5
```{r}
set.seed(1999)
prior <- extract.prior( m11.1 , n=1e4 )
```

#### R code 11.6
```{r}
p <- inv_logit( prior$a )
dens( p , adj=0.1 )
```

#### R code 11.7
```{r}
m11.2 <- quap(alist(
  pulled_left ~ dbinom(1 , p) ,
  logit(p) <- a + b[treatment] ,
  a ~ dnorm(0 , 1.5),
  b[treatment] ~ dnorm(0 , 10)
) ,
data = d)
set.seed(1999)
prior <- extract.prior(m11.2 , n = 1e4)
p <- sapply(1:4 , function(k)
  inv_logit(prior$a + prior$b[, k]))
```

#### R code 11.8
```{r}
dens( abs( p[,1] - p[,2] ) , adj=0.1 )
```

#### R code 11.9
```{r}
m11.3 <- quap(alist(
  pulled_left ~ dbinom(1 , p) ,
  logit(p) <- a + b[treatment] ,
  a ~ dnorm(0 , 1.5),
  b[treatment] ~ dnorm(0 , 0.5)
) ,
data = d)
set.seed(1999)
prior <- extract.prior(m11.3 , n = 1e4)
p <- sapply(1:4 , function(k)
  inv_logit(prior$a + prior$b[, k]))
mean(abs(p[, 1] - p[, 2]))
```

#### R code 11.10
```{r}
# prior trimmed data list
dat_list <- list(
  pulled_left = d$pulled_left,
  actor = d$actor,
  treatment = as.integer(d$treatment)
)
```

#### R code 11.11
```{r}
m11.4 <- ulam(
  alist(
    pulled_left ~ dbinom(1 , p) ,
    logit(p) <- a[actor] + b[treatment] ,
    a[actor] ~ dnorm(0 , 1.5),
    b[treatment] ~ dnorm(0 , 0.5)
  ) ,
  data = dat_list ,
  chains = 4 ,
  log_lik = TRUE
)
precis(m11.4 , depth = 2)
```

```{r}
stancode(m11.4)
```

#### R code 11.12
```{r}
post <- extract.samples(m11.4)
p_left <- inv_logit( post$a )
plot( precis( as.data.frame(p_left) ) , xlim=c(0,1) )
```

#### R code 11.13
```{r}
labs <- c("R/N","L/N","R/P","L/P")
plot( precis( m11.4 , depth=2 , pars="b" ) , labels=labs )
```

#### R code 11.14
```{r}
diffs <- list(db13 = post$b[, 1] - post$b[, 3],
              db24 = post$b[, 2] - post$b[, 4])
plot(precis(diffs))
```

#### R code 11.15
```{r}
pl <- by( d$pulled_left , list( d$actor , d$treatment ) , mean )
pl[1,]
```

#### R code 11.16
```{r}
plot(
  NULL ,
  xlim = c(1, 28) ,
  ylim = c(0, 1) ,
  xlab = "" ,
  ylab = "proportion left lever" ,
  xaxt = "n" ,
  yaxt = "n"
)
axis(2 , at = c(0, 0.5, 1) , labels = c(0, 0.5, 1))
abline(h = 0.5 , lty = 2)
for (j in 1:7)
  abline(v = (j - 1) * 4 + 4.5 , lwd = 0.5)
for (j in 1:7)
  text((j - 1) * 4 + 2.5 , 1.1 , concat("actor ", j) , xpd = TRUE)
for (j in (1:7)[-2]) {
  lines((j - 1) * 4 + c(1, 3) , pl[j, c(1, 3)] , lwd = 2 , col = rangi2)
  lines((j - 1) * 4 + c(2, 4) , pl[j, c(2, 4)] , lwd = 2 , col = rangi2)
}
points(1:28 ,
       t(pl) ,
       pch = 16 ,
       col = "white" ,
       cex = 1.7)
points(1:28 ,
       t(pl) ,
       pch = c(1, 1, 16, 16) ,
       col = rangi2 ,
       lwd = 2)
yoff <- 0.01
text(1 , pl[1, 1] - yoff , "R/N" , pos = 1 , cex = 0.8)
text(2 , pl[1, 2] + yoff , "L/N" , pos = 3 , cex = 0.8)
text(3 , pl[1, 3] - yoff , "R/P" , pos = 1 , cex = 0.8)
text(4 , pl[1, 4] + yoff , "L/P" , pos = 3 , cex = 0.8)
mtext("observed proportions\n")
```

#### R code 11.17
```{r}
dat <- list( actor=rep(1:7,each=4) , treatment=rep(1:4,times=7) )
p_post <- link( m11.4 , data=dat )
p_mu <- apply( p_post , 2 , mean )
p_ci <- apply( p_post , 2 , PI )
```

#### R code 11.18
```{r}
d$side <- d$prosoc_left + 1 # right 1, left 2
d$cond <- d$condition + 1 # no partner 1, partner 2
```

#### R code 11.19
```{r}
dat_list2 <- list(
  pulled_left = d$pulled_left,
  actor = d$actor,
  side = d$side,
  cond = d$cond
)
m11.5 <- ulam(
  alist(
    pulled_left ~ dbinom(1 , p) ,
    logit(p) <- a[actor] + bs[side] + bc[cond] ,
    a[actor] ~ dnorm(0 , 1.5),
    bs[side] ~ dnorm(0 , 0.5),
    bc[cond] ~ dnorm(0 , 0.5)
  ) ,
  data = dat_list2 ,
  chains = 4 ,
  log_lik = TRUE
)
```

#### R code 11.20
```{r}
compare( m11.5 , m11.4 , func=PSIS )
```

#### R code 11.21
```{r}
post <- extract.samples( m11.4 , clean=FALSE )
str(post)
```

#### R code 11.22
```{r}
m11.4_stan_code <- stancode(m11.4)
m11.4_stan <-
  stan(model_code = m11.4_stan_code ,
       data = dat_list ,
       chains = 4)
compare(m11.4_stan , m11.4)
```

### 11.1.2. Relative shark and absolute penguin
