---
title: "10_18_2019_Notes"
author: "John D."
date: "October 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rethinking)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
Sys.setenv(LOCAL_CPPFLAGS = '-march=native')
```

# 10 Big Entropy and the Generalized Linear Model
## 10.1. Maximum entropy

```{r}
p <- list()
p$A <- c(0,0,10,0,0)
p$B <- c(0,1,8,1,0)
p$C <- c(0,2,6,2,0)
p$D <- c(1,2,4,2,1)
p$E <- c(2,2,2,2,2)
p

p_norm <- lapply( p , function(q) q/sum(q))
p_norm

( H <- sapply( p_norm , function(q) -sum(ifelse(q==0,0,q*log(q))) ) )

ways <- c(1,90,1260,37800,113400)
logwayspp <- log(ways)/10
logwayspp

plot(logwayspp,H)
lines(0:2,0:2)
```

## 10.1.2. Binomial

```{r}
 # build list of the candidate distributions
p <- list()
p[[1]] <- c(1/4,1/4,1/4,1/4)
p[[2]] <- c(2/6,1/6,1/6,2/6)
p[[3]] <- c(1/6,2/6,2/6,1/6)
p[[4]] <- c(1/8,4/8,2/8,1/8)
p

sapply( p , function(p) sum(p*c(0,1,1,2)) )

sapply( p , function(p) -sum( p*log(p) ) )

p <- 0.7
( A <- c( (1-p)^2 , p*(1-p) , (1-p)*p , p^2 ) )

-sum( A*log(A) )

sim.p <- function(G=1.4) {
x123 <- runif(3)
x4 <- ( (G)*sum(x123)-x123[2]-x123[3] )/(2-G)
z <- sum( c(x123,x4) )
p <- c( x123 , x4 )/z
list( H=-sum( p*log(p) ) , p=p )
}

H <- replicate( 1e5 , sim.p(1.4) )
dens( as.numeric(H[1,]) , adj=0.1 )

entropies <- as.numeric(H[1,])
distributions <- H[2,]

max(entropies)

distributions[ which.max(entropies) ]
```

